
import { StyleSheet } from '@react-pdf/renderer';
import { CORES } from './constants';

export const styles = StyleSheet.create({
  // Portrait padrão
  page: {
    flexDirection: 'column',
    backgroundColor: 'white',
    padding: 30,
    fontSize: 12,
    fontFamily: 'Helvetica',
  },
  // --- LANDSCAPE ---
  pageLandscape: {
    width: 841.89,
    height: 595.28,
    padding: '34 40',
    fontFamily: 'Helvetica',
    backgroundColor: '#f7fafd',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
    paddingBottom: 15,
    borderBottomWidth: 2,
    borderBottomColor: CORES.primary,
    borderBottomStyle: 'solid',
  },
  headerLandscape: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 18,
    paddingBottom: 12,
    borderBottomWidth: 2,
    borderBottomColor: CORES.primary,
    borderBottomStyle: 'solid',
    backgroundColor: '#f0f5ff',
    borderRadius: 4,
  },
  companyInfo: { maxWidth: 250 },
  logo: { width: 200, height: 60, marginBottom: 10, objectFit: 'contain' },
  companyDetails: {
    fontSize: 8,
    color: CORES.secondary,
    lineHeight: 1.3,
  },
  documentInfo: {
    alignItems: 'flex-end',
  },
  documentInfoLandscape: {
    alignItems: 'flex-end',
  },
  documentTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: CORES.primary,
    marginBottom: 5,
  },
  reportTitleLandscape: {
    fontSize: 28,
    fontWeight: 'bold',
    color: CORES.primary,
    marginBottom: 2,
    letterSpacing: 0.6,
  },
  reportMetaLandscape: {
    fontSize: 10,
    color: CORES.secondary,
    marginBottom: 2,
  },
  filterInfoLandscape: {
    fontSize: 9,
    color: CORES.primary,
    backgroundColor: '#e5edfc',
    marginTop: 10,
    marginBottom: 10,
    padding: 8,
    borderRadius: 6,
    borderLeftWidth: 4,
    borderLeftColor: CORES.primary,
  },
  tableContainerLandscape: {
    marginTop: 10,
    marginBottom: 10,
    borderRadius: 8,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e6e6ef',
    overflow: 'hidden',
  },
  tableHeaderLandscape: {
    flexDirection: 'row',
    backgroundColor: CORES.primary,
    alignItems: 'center',
    paddingVertical: 10,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
  },
  tableRowLandscape: {
    flexDirection: 'row',
    paddingVertical: 9,
    alignItems: 'center',
    minHeight: 28,
    borderBottomWidth: 1,
    borderBottomColor: "#e0e5f5",
  },
  headerTextLandscape: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#fff',
    textAlign: 'center',
    letterSpacing: 0.2,
    width: '100%',
  },
  cellTextLandscape: {
    fontSize: 9,
    color: '#2d3748',
    textAlign: 'center',
    width: '100%',
  },
  idColumnLandscape: {
    width: '13%',
    paddingHorizontal: 5,
  },
  entityColumnLandscape: {
    width: '17%',
    paddingHorizontal: 6,
    textAlign: 'left',
  },
  weightColumnLandscape: {
    width: '10%',
    paddingHorizontal: 4,
    textAlign: 'right',
  },
  volumeColumnLandscape: {
    width: '12%',
    paddingHorizontal: 2,
    textAlign: 'right',
  },
  valueColumnLandscape: {
    width: '14%',
    paddingHorizontal: 6,
    textAlign: 'right',
  },
  dateColumnLandscape: {
    width: '11%',
    paddingHorizontal: 4,
    textAlign: 'center',
  },
  entityNameTextLandscape: {
    fontSize: 9,
    fontWeight: 'semibold',
    marginBottom: 2,
    color: '#3b4095',
    textAlign: 'left',
  },
  entityDocTextLandscape: {
    fontSize: 8,
    color: '#8d99af',
    textAlign: 'left',
  },
  numericTextLandscape: {
    fontSize: 9,
    textAlign: 'right',
    fontFamily: 'Helvetica-Bold',
    color: '#0057d8',
  },
  summaryBoxLandscape: {
    marginTop: 16,
    marginBottom: 10,
    padding: 10,
    backgroundColor: '#f0f5ff',
    borderRadius: 6,
    alignSelf: 'flex-end',
    width: 380,
    shadowColor: '#dbeafe',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 2,
    borderWidth: 1,
    borderColor: CORES.primary,
  },
  summaryTitleLandscape: {
    fontSize: 12,
    fontWeight: 'bold',
    marginBottom: 6,
    color: '#2d3748',
    letterSpacing: 0.2,
  },
  summaryItemLandscape: {
    fontSize: 10,
    color: "#495674",
    marginBottom: 2,
    lineHeight: 1.4,
  },
  footerLandscape: {
    position: 'absolute',
    bottom: 32,
    left: 40,
    right: 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 11,
    borderTopWidth: 1,
    borderTopColor: "#dbeafe",
  },
  footerTextLandscape: {
    fontSize: 9,
    color: '#a0aec0',
  },
  pageNumberLandscape: {
    position: 'absolute',
    fontSize: 8,
    bottom: 20,
    left: 0,
    right: 0,
    textAlign: 'center',
    color: 'grey',
  },
  // ---- RESTANTE PADRÃO ---------
  messageContainer: {
    padding: 15,
    backgroundColor: CORES.light,
    borderRadius: 5,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: CORES.border,
  },
  messageText: {
    fontSize: 12,
    lineHeight: 1.5,
    color: CORES.secondary,
  },
  proposalItem: {
    marginBottom: 12,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#edf2f7',
    borderBottomStyle: 'solid',
  },
  highlightedValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: CORES.primary,
  },
  // --- Report PDF additions from reportStyles ---
  reportTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: CORES.primary,
    marginBottom: 8,
  },
  reportMeta: {
    fontSize: 8,
    color: CORES.secondary,
    marginBottom: 15,
  },
  filterInfo: {
    fontSize: 7,
    color: CORES.secondary,
    marginBottom: 10,
    padding: 6,
    backgroundColor: '#f7f7f7',
    borderRadius: 4,
    borderLeft: `3px solid ${CORES.primary}`,
  },
  tableContainer: {
    marginTop: 15,
    marginBottom: 15,
  },
  pageNumber: {
    position: 'absolute',
    fontSize: 8,
    bottom: 30,
    left: 0,
    right: 0,
    textAlign: 'center',
    color: 'grey',
  },
  summaryBox: {
    marginTop: 20,
    padding: 8,
    backgroundColor: '#f0f5ff',
    borderRadius: 4,
  },
  summaryTitle: {
    fontSize: 11,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  summaryItem: {
    fontSize: 9,
    marginBottom: 2,
  },
  tableHeader: {
    // This is the overriding (last) definition used!
    flexDirection: 'row',
    backgroundColor: CORES.primary,
    alignItems: 'center',
    paddingVertical: 8,
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
  },
  tableRow: {
    // This is the overriding (last) definition used!
    flexDirection: 'row',
    paddingVertical: 8,
    borderBottomWidth: 0.5,
    borderBottomColor: '#e2e8f0',
    alignItems: 'center',
    minHeight: 32,
  },
  headerCell: {
    flex: 1,
    color: '#3b4095',
    fontSize: 9,
    fontWeight: 'bold',
    textAlign: 'left',
    paddingHorizontal: 4,
  },
  tableCell: {
    flex: 1,
    fontSize: 10,
    color: CORES.secondary,
    textAlign: 'left',
    paddingHorizontal: 4,
  },
  idColumn: {
    width: '17%',
    paddingHorizontal: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  entityColumn: {
    width: '17%',
    paddingHorizontal: 4,
  },
  weightColumn: {
    width: '8%',
    paddingHorizontal: 4,
  },
  volumeColumn: {
    width: '8%',
    paddingHorizontal: 4,
  },
  valueColumn: {
    width: '15%',
    paddingHorizontal: 4,
  },
  dateColumn: {
    width: '10%',
    paddingHorizontal: 4,
  },
  headerText: {
    fontSize: 9,
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  cellText: {
    fontSize: 8,
    color: CORES.secondary,
  },
  numericText: {
    fontSize: 8,
    textAlign: 'right',
    fontFamily: 'Helvetica-Bold',
  },
  entityNameText: {
    fontSize: 8,
    marginBottom: 2,
  },
  entityDocText: {
    fontSize: 7,
    color: '#666',
  },
  content: {
    padding: 12,
    flexDirection: 'column',
    gap: 12,
  },
  documentMeta: {
    fontSize: 10,
    color: CORES.secondary,
    marginBottom: 12,
    textAlign: 'right',
  },
  section: {
    marginBottom: 16,
    padding: 10,
    backgroundColor: '#f7fafd',
    borderRadius: 6,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: CORES.primary,
    marginBottom: 8,
  },
  twoColumn: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 10,
  },
  column: {
    flex: 1,
    flexDirection: "column",
    gap: 6,
  },
  infoItem: {
    marginBottom: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  label: {
    fontSize: 10,
    color: '#6b7280',
    fontWeight: "bold",
    marginRight: 4,
    minWidth: 72,
  },
  value: {
    fontSize: 10,
    color: '#23272f',
    fontWeight: "normal",
  },
  footer: {
    marginTop: 30,
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    borderTopStyle: 'solid',
    paddingTop: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  footerText: {
    fontSize: 9,
    color: CORES.secondary,
  },
  // -- MISSING STYLE KEYS FOR PDF COMPONENTS --
  table: {
    width: '100%',
    borderRadius: 4,
    overflow: 'hidden',
    backgroundColor: '#fff',
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  notesContainer: {
    padding: 10,
    backgroundColor: '#f8fafc',
    borderLeftWidth: 4,
    borderLeftColor: CORES.primary,
    borderRadius: 5,
    marginTop: 8,
    marginBottom: 8,
  },
  notesTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: CORES.primary,
    marginBottom: 5,
  },
  card: {
    padding: 12,
    backgroundColor: '#f5f7fa',
    borderRadius: 5,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    boxSizing: 'border-box',
  },
  cardTitle: {
    fontSize: 11,
    fontWeight: 'bold',
    color: CORES.primary,
    marginBottom: 6,
  },
});
